
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("4d7ec033-39a0-41fe-b74d-ca5135115d6d")>

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class MrpPosEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new MrpPosEntities object using the connection string found in the 'MrpPosEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=MrpPosEntities", "MrpPosEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new MrpPosEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "MrpPosEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new MrpPosEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "MrpPosEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property mrp_prod_lot() As ObjectSet(Of mrp_prod_lot)
        Get
            If (_mrp_prod_lot Is Nothing) Then
                _mrp_prod_lot = MyBase.CreateObjectSet(Of mrp_prod_lot)("mrp_prod_lot")
            End If
            Return _mrp_prod_lot
        End Get
    End Property

    Private _mrp_prod_lot As ObjectSet(Of mrp_prod_lot)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property user_user() As ObjectSet(Of user_user)
        Get
            If (_user_user Is Nothing) Then
                _user_user = MyBase.CreateObjectSet(Of user_user)("user_user")
            End If
            Return _user_user
        End Get
    End Property

    Private _user_user As ObjectSet(Of user_user)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property product_product() As ObjectSet(Of product_product)
        Get
            If (_product_product Is Nothing) Then
                _product_product = MyBase.CreateObjectSet(Of product_product)("product_product")
            End If
            Return _product_product
        End Get
    End Property

    Private _product_product As ObjectSet(Of product_product)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property mrp_order_line() As ObjectSet(Of mrp_order_line)
        Get
            If (_mrp_order_line Is Nothing) Then
                _mrp_order_line = MyBase.CreateObjectSet(Of mrp_order_line)("mrp_order_line")
            End If
            Return _mrp_order_line
        End Get
    End Property

    Private _mrp_order_line As ObjectSet(Of mrp_order_line)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property mrp_order_case() As ObjectSet(Of mrp_order_case)
        Get
            If (_mrp_order_case Is Nothing) Then
                _mrp_order_case = MyBase.CreateObjectSet(Of mrp_order_case)("mrp_order_case")
            End If
            Return _mrp_order_case
        End Get
    End Property

    Private _mrp_order_case As ObjectSet(Of mrp_order_case)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property mrp_order() As ObjectSet(Of mrp_order)
        Get
            If (_mrp_order Is Nothing) Then
                _mrp_order = MyBase.CreateObjectSet(Of mrp_order)("mrp_order")
            End If
            Return _mrp_order
        End Get
    End Property

    Private _mrp_order As ObjectSet(Of mrp_order)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property product_case() As ObjectSet(Of product_case)
        Get
            If (_product_case Is Nothing) Then
                _product_case = MyBase.CreateObjectSet(Of product_case)("product_case")
            End If
            Return _product_case
        End Get
    End Property

    Private _product_case As ObjectSet(Of product_case)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property mrp_case_piece() As ObjectSet(Of mrp_case_piece)
        Get
            If (_mrp_case_piece Is Nothing) Then
                _mrp_case_piece = MyBase.CreateObjectSet(Of mrp_case_piece)("mrp_case_piece")
            End If
            Return _mrp_case_piece
        End Get
    End Property

    Private _mrp_case_piece As ObjectSet(Of mrp_case_piece)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the mrp_prod_lot EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTomrp_prod_lot(ByVal mrp_prod_lot As mrp_prod_lot)
        MyBase.AddObject("mrp_prod_lot", mrp_prod_lot)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the user_user EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTouser_user(ByVal user_user As user_user)
        MyBase.AddObject("user_user", user_user)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the product_product EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToproduct_product(ByVal product_product As product_product)
        MyBase.AddObject("product_product", product_product)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the mrp_order_line EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTomrp_order_line(ByVal mrp_order_line As mrp_order_line)
        MyBase.AddObject("mrp_order_line", mrp_order_line)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the mrp_order_case EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTomrp_order_case(ByVal mrp_order_case As mrp_order_case)
        MyBase.AddObject("mrp_order_case", mrp_order_case)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the mrp_order EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTomrp_order(ByVal mrp_order As mrp_order)
        MyBase.AddObject("mrp_order", mrp_order)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the product_case EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToproduct_case(ByVal product_case As product_case)
        MyBase.AddObject("product_case", product_case)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the mrp_case_piece EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTomrp_case_piece(ByVal mrp_case_piece As mrp_case_piece)
        MyBase.AddObject("mrp_case_piece", mrp_case_piece)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MrpPosModel", Name:="mrp_case_piece")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class mrp_case_piece
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new mrp_case_piece object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    Public Shared Function Createmrp_case_piece(id As Global.System.Int64) As mrp_case_piece
        Dim mrp_case_piece as mrp_case_piece = New mrp_case_piece
        mrp_case_piece.id = id
        Return mrp_case_piece
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int64
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int64
    Private Partial Sub OnidChanging(value As Global.System.Int64)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property case_id() As Nullable(Of Global.System.Int64)
        Get
            Return _case_id
        End Get
        Set
            Oncase_idChanging(value)
            ReportPropertyChanging("case_id")
            _case_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("case_id")
            Oncase_idChanged()
        End Set
    End Property

    Private _case_id As Nullable(Of Global.System.Int64)
    Private Partial Sub Oncase_idChanging(value As Nullable(Of Global.System.Int64))
    End Sub

    Private Partial Sub Oncase_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property order_id() As Nullable(Of Global.System.Int64)
        Get
            Return _order_id
        End Get
        Set
            Onorder_idChanging(value)
            ReportPropertyChanging("order_id")
            _order_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("order_id")
            Onorder_idChanged()
        End Set
    End Property

    Private _order_id As Nullable(Of Global.System.Int64)
    Private Partial Sub Onorder_idChanging(value As Nullable(Of Global.System.Int64))
    End Sub

    Private Partial Sub Onorder_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property create_by() As Nullable(Of Global.System.Int64)
        Get
            Return _create_by
        End Get
        Set
            Oncreate_byChanging(value)
            ReportPropertyChanging("create_by")
            _create_by = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("create_by")
            Oncreate_byChanged()
        End Set
    End Property

    Private _create_by As Nullable(Of Global.System.Int64)
    Private Partial Sub Oncreate_byChanging(value As Nullable(Of Global.System.Int64))
    End Sub

    Private Partial Sub Oncreate_byChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property create_date() As Nullable(Of Global.System.DateTime)
        Get
            Return _create_date
        End Get
        Set
            Oncreate_dateChanging(value)
            ReportPropertyChanging("create_date")
            _create_date = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("create_date")
            Oncreate_dateChanged()
        End Set
    End Property

    Private _create_date As Nullable(Of Global.System.DateTime)
    Private Partial Sub Oncreate_dateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Oncreate_dateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property write_by() As Nullable(Of Global.System.Int64)
        Get
            Return _write_by
        End Get
        Set
            Onwrite_byChanging(value)
            ReportPropertyChanging("write_by")
            _write_by = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("write_by")
            Onwrite_byChanged()
        End Set
    End Property

    Private _write_by As Nullable(Of Global.System.Int64)
    Private Partial Sub Onwrite_byChanging(value As Nullable(Of Global.System.Int64))
    End Sub

    Private Partial Sub Onwrite_byChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property write_date() As Nullable(Of Global.System.DateTime)
        Get
            Return _write_date
        End Get
        Set
            Onwrite_dateChanging(value)
            ReportPropertyChanging("write_date")
            _write_date = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("write_date")
            Onwrite_dateChanged()
        End Set
    End Property

    Private _write_date As Nullable(Of Global.System.DateTime)
    Private Partial Sub Onwrite_dateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Onwrite_dateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property line_id() As Nullable(Of Global.System.Int64)
        Get
            Return _line_id
        End Get
        Set
            Online_idChanging(value)
            ReportPropertyChanging("line_id")
            _line_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("line_id")
            Online_idChanged()
        End Set
    End Property

    Private _line_id As Nullable(Of Global.System.Int64)
    Private Partial Sub Online_idChanging(value As Nullable(Of Global.System.Int64))
    End Sub

    Private Partial Sub Online_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property status() As Nullable(Of Global.System.Int32)
        Get
            Return _status
        End Get
        Set
            OnstatusChanging(value)
            ReportPropertyChanging("status")
            _status = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("status")
            OnstatusChanged()
        End Set
    End Property

    Private _status As Nullable(Of Global.System.Int32)
    Private Partial Sub OnstatusChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnstatusChanged()
    End Sub

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MrpPosModel", Name:="mrp_order")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class mrp_order
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new mrp_order object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    Public Shared Function Createmrp_order(id As Global.System.Int64) As mrp_order
        Dim mrp_order as mrp_order = New mrp_order
        mrp_order.id = id
        Return mrp_order
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property name() As Global.System.String
        Get
            Return _name
        End Get
        Set
            OnnameChanging(value)
            ReportPropertyChanging("name")
            _name = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("name")
            OnnameChanged()
        End Set
    End Property

    Private _name As Global.System.String
    Private Partial Sub OnnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property workstation_id() As Global.System.String
        Get
            Return _workstation_id
        End Get
        Set
            Onworkstation_idChanging(value)
            ReportPropertyChanging("workstation_id")
            _workstation_id = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("workstation_id")
            Onworkstation_idChanged()
        End Set
    End Property

    Private _workstation_id As Global.System.String
    Private Partial Sub Onworkstation_idChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onworkstation_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property date_order() As Nullable(Of Global.System.DateTime)
        Get
            Return _date_order
        End Get
        Set
            Ondate_orderChanging(value)
            ReportPropertyChanging("date_order")
            _date_order = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("date_order")
            Ondate_orderChanged()
        End Set
    End Property

    Private _date_order As Nullable(Of Global.System.DateTime)
    Private Partial Sub Ondate_orderChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Ondate_orderChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property nb_print() As Global.System.String
        Get
            Return _nb_print
        End Get
        Set
            Onnb_printChanging(value)
            ReportPropertyChanging("nb_print")
            _nb_print = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("nb_print")
            Onnb_printChanged()
        End Set
    End Property

    Private _nb_print As Global.System.String
    Private Partial Sub Onnb_printChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onnb_printChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property lot_id() As Nullable(Of Global.System.Int32)
        Get
            Return _lot_id
        End Get
        Set
            Onlot_idChanging(value)
            ReportPropertyChanging("lot_id")
            _lot_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("lot_id")
            Onlot_idChanged()
        End Set
    End Property

    Private _lot_id As Nullable(Of Global.System.Int32)
    Private Partial Sub Onlot_idChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onlot_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property state() As Global.System.String
        Get
            Return _state
        End Get
        Set
            OnstateChanging(value)
            ReportPropertyChanging("state")
            _state = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("state")
            OnstateChanged()
        End Set
    End Property

    Private _state As Global.System.String
    Private Partial Sub OnstateChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnstateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property create_date() As Nullable(Of Global.System.DateTime)
        Get
            Return _create_date
        End Get
        Set
            Oncreate_dateChanging(value)
            ReportPropertyChanging("create_date")
            _create_date = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("create_date")
            Oncreate_dateChanged()
        End Set
    End Property

    Private _create_date As Nullable(Of Global.System.DateTime)
    Private Partial Sub Oncreate_dateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Oncreate_dateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property create_uid() As Nullable(Of Global.System.Int32)
        Get
            Return _create_uid
        End Get
        Set
            Oncreate_uidChanging(value)
            ReportPropertyChanging("create_uid")
            _create_uid = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("create_uid")
            Oncreate_uidChanged()
        End Set
    End Property

    Private _create_uid As Nullable(Of Global.System.Int32)
    Private Partial Sub Oncreate_uidChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Oncreate_uidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property write_date() As Nullable(Of Global.System.DateTime)
        Get
            Return _write_date
        End Get
        Set
            Onwrite_dateChanging(value)
            ReportPropertyChanging("write_date")
            _write_date = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("write_date")
            Onwrite_dateChanged()
        End Set
    End Property

    Private _write_date As Nullable(Of Global.System.DateTime)
    Private Partial Sub Onwrite_dateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Onwrite_dateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property write_uid() As Nullable(Of Global.System.Int32)
        Get
            Return _write_uid
        End Get
        Set
            Onwrite_uidChanging(value)
            ReportPropertyChanging("write_uid")
            _write_uid = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("write_uid")
            Onwrite_uidChanged()
        End Set
    End Property

    Private _write_uid As Nullable(Of Global.System.Int32)
    Private Partial Sub Onwrite_uidChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onwrite_uidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property product_id() As Nullable(Of Global.System.Int64)
        Get
            Return _product_id
        End Get
        Set
            Onproduct_idChanging(value)
            ReportPropertyChanging("product_id")
            _product_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("product_id")
            Onproduct_idChanged()
        End Set
    End Property

    Private _product_id As Nullable(Of Global.System.Int64)
    Private Partial Sub Onproduct_idChanging(value As Nullable(Of Global.System.Int64))
    End Sub

    Private Partial Sub Onproduct_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property total_pcs() As Nullable(Of Global.System.Int64)
        Get
            Return _total_pcs
        End Get
        Set
            Ontotal_pcsChanging(value)
            ReportPropertyChanging("total_pcs")
            _total_pcs = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("total_pcs")
            Ontotal_pcsChanged()
        End Set
    End Property

    Private _total_pcs As Nullable(Of Global.System.Int64)
    Private Partial Sub Ontotal_pcsChanging(value As Nullable(Of Global.System.Int64))
    End Sub

    Private Partial Sub Ontotal_pcsChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property total_weight() As Nullable(Of Global.System.Int64)
        Get
            Return _total_weight
        End Get
        Set
            Ontotal_weightChanging(value)
            ReportPropertyChanging("total_weight")
            _total_weight = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("total_weight")
            Ontotal_weightChanged()
        End Set
    End Property

    Private _total_weight As Nullable(Of Global.System.Int64)
    Private Partial Sub Ontotal_weightChanging(value As Nullable(Of Global.System.Int64))
    End Sub

    Private Partial Sub Ontotal_weightChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property total_cases() As Nullable(Of Global.System.Int64)
        Get
            Return _total_cases
        End Get
        Set
            Ontotal_casesChanging(value)
            ReportPropertyChanging("total_cases")
            _total_cases = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("total_cases")
            Ontotal_casesChanged()
        End Set
    End Property

    Private _total_cases As Nullable(Of Global.System.Int64)
    Private Partial Sub Ontotal_casesChanging(value As Nullable(Of Global.System.Int64))
    End Sub

    Private Partial Sub Ontotal_casesChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int64
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int64
    Private Partial Sub OnidChanging(value As Global.System.Int64)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property printPrice() As Nullable(Of Global.System.Int32)
        Get
            Return _printPrice
        End Get
        Set
            OnprintPriceChanging(value)
            ReportPropertyChanging("printPrice")
            _printPrice = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("printPrice")
            OnprintPriceChanged()
        End Set
    End Property

    Private _printPrice As Nullable(Of Global.System.Int32)
    Private Partial Sub OnprintPriceChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnprintPriceChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property printCase() As Nullable(Of Global.System.Int32)
        Get
            Return _printCase
        End Get
        Set
            OnprintCaseChanging(value)
            ReportPropertyChanging("printCase")
            _printCase = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("printCase")
            OnprintCaseChanged()
        End Set
    End Property

    Private _printCase As Nullable(Of Global.System.Int32)
    Private Partial Sub OnprintCaseChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnprintCaseChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property case_product_id() As Nullable(Of Global.System.Int32)
        Get
            Return _case_product_id
        End Get
        Set
            Oncase_product_idChanging(value)
            ReportPropertyChanging("case_product_id")
            _case_product_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("case_product_id")
            Oncase_product_idChanged()
        End Set
    End Property

    Private _case_product_id As Nullable(Of Global.System.Int32)
    Private Partial Sub Oncase_product_idChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Oncase_product_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property pcs_per_case() As Nullable(Of Global.System.Int32)
        Get
            Return _pcs_per_case
        End Get
        Set
            Onpcs_per_caseChanging(value)
            ReportPropertyChanging("pcs_per_case")
            _pcs_per_case = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("pcs_per_case")
            Onpcs_per_caseChanged()
        End Set
    End Property

    Private _pcs_per_case As Nullable(Of Global.System.Int32)
    Private Partial Sub Onpcs_per_caseChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onpcs_per_caseChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property printSlogan() As Nullable(Of Global.System.Int32)
        Get
            Return _printSlogan
        End Get
        Set
            OnprintSloganChanging(value)
            ReportPropertyChanging("printSlogan")
            _printSlogan = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("printSlogan")
            OnprintSloganChanged()
        End Set
    End Property

    Private _printSlogan As Nullable(Of Global.System.Int32)
    Private Partial Sub OnprintSloganChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnprintSloganChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property caseprice() As Nullable(Of Global.System.Int32)
        Get
            Return _caseprice
        End Get
        Set
            OncasepriceChanging(value)
            ReportPropertyChanging("caseprice")
            _caseprice = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("caseprice")
            OncasepriceChanged()
        End Set
    End Property

    Private _caseprice As Nullable(Of Global.System.Int32)
    Private Partial Sub OncasepriceChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OncasepriceChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property print_summary() As Nullable(Of Global.System.Int32)
        Get
            Return _print_summary
        End Get
        Set
            Onprint_summaryChanging(value)
            ReportPropertyChanging("print_summary")
            _print_summary = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("print_summary")
            Onprint_summaryChanged()
        End Set
    End Property

    Private _print_summary As Nullable(Of Global.System.Int32)
    Private Partial Sub Onprint_summaryChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onprint_summaryChanged()
    End Sub

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MrpPosModel", Name:="mrp_order_case")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class mrp_order_case
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new mrp_order_case object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    Public Shared Function Createmrp_order_case(id As Global.System.Int64) As mrp_order_case
        Dim mrp_order_case as mrp_order_case = New mrp_order_case
        mrp_order_case.id = id
        Return mrp_order_case
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property no_of_pcs() As Nullable(Of Global.System.Int32)
        Get
            Return _no_of_pcs
        End Get
        Set
            Onno_of_pcsChanging(value)
            ReportPropertyChanging("no_of_pcs")
            _no_of_pcs = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("no_of_pcs")
            Onno_of_pcsChanged()
        End Set
    End Property

    Private _no_of_pcs As Nullable(Of Global.System.Int32)
    Private Partial Sub Onno_of_pcsChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onno_of_pcsChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property qty() As Nullable(Of Global.System.Int64)
        Get
            Return _qty
        End Get
        Set
            OnqtyChanging(value)
            ReportPropertyChanging("qty")
            _qty = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("qty")
            OnqtyChanged()
        End Set
    End Property

    Private _qty As Nullable(Of Global.System.Int64)
    Private Partial Sub OnqtyChanging(value As Nullable(Of Global.System.Int64))
    End Sub

    Private Partial Sub OnqtyChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property order_id() As Nullable(Of Global.System.Int64)
        Get
            Return _order_id
        End Get
        Set
            Onorder_idChanging(value)
            ReportPropertyChanging("order_id")
            _order_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("order_id")
            Onorder_idChanged()
        End Set
    End Property

    Private _order_id As Nullable(Of Global.System.Int64)
    Private Partial Sub Onorder_idChanging(value As Nullable(Of Global.System.Int64))
    End Sub

    Private Partial Sub Onorder_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property create_date() As Nullable(Of Global.System.DateTime)
        Get
            Return _create_date
        End Get
        Set
            Oncreate_dateChanging(value)
            ReportPropertyChanging("create_date")
            _create_date = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("create_date")
            Oncreate_dateChanged()
        End Set
    End Property

    Private _create_date As Nullable(Of Global.System.DateTime)
    Private Partial Sub Oncreate_dateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Oncreate_dateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property create_id() As Nullable(Of Global.System.Int32)
        Get
            Return _create_id
        End Get
        Set
            Oncreate_idChanging(value)
            ReportPropertyChanging("create_id")
            _create_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("create_id")
            Oncreate_idChanged()
        End Set
    End Property

    Private _create_id As Nullable(Of Global.System.Int32)
    Private Partial Sub Oncreate_idChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Oncreate_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property write_date() As Nullable(Of Global.System.DateTime)
        Get
            Return _write_date
        End Get
        Set
            Onwrite_dateChanging(value)
            ReportPropertyChanging("write_date")
            _write_date = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("write_date")
            Onwrite_dateChanged()
        End Set
    End Property

    Private _write_date As Nullable(Of Global.System.DateTime)
    Private Partial Sub Onwrite_dateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Onwrite_dateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property write_id() As Nullable(Of Global.System.Int32)
        Get
            Return _write_id
        End Get
        Set
            Onwrite_idChanging(value)
            ReportPropertyChanging("write_id")
            _write_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("write_id")
            Onwrite_idChanged()
        End Set
    End Property

    Private _write_id As Nullable(Of Global.System.Int32)
    Private Partial Sub Onwrite_idChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onwrite_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int64
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int64
    Private Partial Sub OnidChanging(value As Global.System.Int64)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property product_id() As Nullable(Of Global.System.Int64)
        Get
            Return _product_id
        End Get
        Set
            Onproduct_idChanging(value)
            ReportPropertyChanging("product_id")
            _product_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("product_id")
            Onproduct_idChanged()
        End Set
    End Property

    Private _product_id As Nullable(Of Global.System.Int64)
    Private Partial Sub Onproduct_idChanging(value As Nullable(Of Global.System.Int64))
    End Sub

    Private Partial Sub Onproduct_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property serial_no() As Global.System.String
        Get
            Return _serial_no
        End Get
        Set
            Onserial_noChanging(value)
            ReportPropertyChanging("serial_no")
            _serial_no = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("serial_no")
            Onserial_noChanged()
        End Set
    End Property

    Private _serial_no As Global.System.String
    Private Partial Sub Onserial_noChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onserial_noChanged()
    End Sub

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MrpPosModel", Name:="mrp_order_line")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class mrp_order_line
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new mrp_order_line object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    Public Shared Function Createmrp_order_line(id As Global.System.Int64) As mrp_order_line
        Dim mrp_order_line as mrp_order_line = New mrp_order_line
        mrp_order_line.id = id
        Return mrp_order_line
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property product_id() As Global.System.String
        Get
            Return _product_id
        End Get
        Set
            Onproduct_idChanging(value)
            ReportPropertyChanging("product_id")
            _product_id = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("product_id")
            Onproduct_idChanged()
        End Set
    End Property

    Private _product_id As Global.System.String
    Private Partial Sub Onproduct_idChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onproduct_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property order_id() As Global.System.String
        Get
            Return _order_id
        End Get
        Set
            Onorder_idChanging(value)
            ReportPropertyChanging("order_id")
            _order_id = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("order_id")
            Onorder_idChanged()
        End Set
    End Property

    Private _order_id As Global.System.String
    Private Partial Sub Onorder_idChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onorder_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property prodlot_id() As Global.System.String
        Get
            Return _prodlot_id
        End Get
        Set
            Onprodlot_idChanging(value)
            ReportPropertyChanging("prodlot_id")
            _prodlot_id = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("prodlot_id")
            Onprodlot_idChanged()
        End Set
    End Property

    Private _prodlot_id As Global.System.String
    Private Partial Sub Onprodlot_idChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onprodlot_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property qty() As Global.System.String
        Get
            Return _qty
        End Get
        Set
            OnqtyChanging(value)
            ReportPropertyChanging("qty")
            _qty = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("qty")
            OnqtyChanged()
        End Set
    End Property

    Private _qty As Global.System.String
    Private Partial Sub OnqtyChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnqtyChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property box_id() As Global.System.String
        Get
            Return _box_id
        End Get
        Set
            Onbox_idChanging(value)
            ReportPropertyChanging("box_id")
            _box_id = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("box_id")
            Onbox_idChanged()
        End Set
    End Property

    Private _box_id As Global.System.String
    Private Partial Sub Onbox_idChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onbox_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property create_date() As Nullable(Of Global.System.DateTime)
        Get
            Return _create_date
        End Get
        Set
            Oncreate_dateChanging(value)
            ReportPropertyChanging("create_date")
            _create_date = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("create_date")
            Oncreate_dateChanged()
        End Set
    End Property

    Private _create_date As Nullable(Of Global.System.DateTime)
    Private Partial Sub Oncreate_dateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Oncreate_dateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property create_uid() As Nullable(Of Global.System.Int32)
        Get
            Return _create_uid
        End Get
        Set
            Oncreate_uidChanging(value)
            ReportPropertyChanging("create_uid")
            _create_uid = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("create_uid")
            Oncreate_uidChanged()
        End Set
    End Property

    Private _create_uid As Nullable(Of Global.System.Int32)
    Private Partial Sub Oncreate_uidChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Oncreate_uidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property write_date() As Nullable(Of Global.System.DateTime)
        Get
            Return _write_date
        End Get
        Set
            Onwrite_dateChanging(value)
            ReportPropertyChanging("write_date")
            _write_date = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("write_date")
            Onwrite_dateChanged()
        End Set
    End Property

    Private _write_date As Nullable(Of Global.System.DateTime)
    Private Partial Sub Onwrite_dateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Onwrite_dateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property write_uid() As Nullable(Of Global.System.Int32)
        Get
            Return _write_uid
        End Get
        Set
            Onwrite_uidChanging(value)
            ReportPropertyChanging("write_uid")
            _write_uid = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("write_uid")
            Onwrite_uidChanged()
        End Set
    End Property

    Private _write_uid As Nullable(Of Global.System.Int32)
    Private Partial Sub Onwrite_uidChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onwrite_uidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property price() As Nullable(Of Global.System.Decimal)
        Get
            Return _price
        End Get
        Set
            OnpriceChanging(value)
            ReportPropertyChanging("price")
            _price = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("price")
            OnpriceChanged()
        End Set
    End Property

    Private _price As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnpriceChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnpriceChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int64
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int64
    Private Partial Sub OnidChanging(value As Global.System.Int64)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property serial_no() As Global.System.String
        Get
            Return _serial_no
        End Get
        Set
            Onserial_noChanging(value)
            ReportPropertyChanging("serial_no")
            _serial_no = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("serial_no")
            Onserial_noChanged()
        End Set
    End Property

    Private _serial_no As Global.System.String
    Private Partial Sub Onserial_noChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onserial_noChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property prefix() As Global.System.String
        Get
            Return _prefix
        End Get
        Set
            OnprefixChanging(value)
            ReportPropertyChanging("prefix")
            _prefix = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("prefix")
            OnprefixChanged()
        End Set
    End Property

    Private _prefix As Global.System.String
    Private Partial Sub OnprefixChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnprefixChanged()
    End Sub

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MrpPosModel", Name:="mrp_prod_lot")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class mrp_prod_lot
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new mrp_prod_lot object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    Public Shared Function Createmrp_prod_lot(id As Global.System.Int64) As mrp_prod_lot
        Dim mrp_prod_lot as mrp_prod_lot = New mrp_prod_lot
        mrp_prod_lot.id = id
        Return mrp_prod_lot
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property name() As Global.System.String
        Get
            Return _name
        End Get
        Set
            OnnameChanging(value)
            ReportPropertyChanging("name")
            _name = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("name")
            OnnameChanged()
        End Set
    End Property

    Private _name As Global.System.String
    Private Partial Sub OnnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property expired_date() As Nullable(Of Global.System.DateTime)
        Get
            Return _expired_date
        End Get
        Set
            Onexpired_dateChanging(value)
            ReportPropertyChanging("expired_date")
            _expired_date = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("expired_date")
            Onexpired_dateChanged()
        End Set
    End Property

    Private _expired_date As Nullable(Of Global.System.DateTime)
    Private Partial Sub Onexpired_dateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Onexpired_dateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property manufacturing_date() As Global.System.String
        Get
            Return _manufacturing_date
        End Get
        Set
            Onmanufacturing_dateChanging(value)
            ReportPropertyChanging("manufacturing_date")
            _manufacturing_date = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("manufacturing_date")
            Onmanufacturing_dateChanged()
        End Set
    End Property

    Private _manufacturing_date As Global.System.String
    Private Partial Sub Onmanufacturing_dateChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onmanufacturing_dateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property day_to_expiry() As Global.System.String
        Get
            Return _day_to_expiry
        End Get
        Set
            Onday_to_expiryChanging(value)
            ReportPropertyChanging("day_to_expiry")
            _day_to_expiry = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("day_to_expiry")
            Onday_to_expiryChanged()
        End Set
    End Property

    Private _day_to_expiry As Global.System.String
    Private Partial Sub Onday_to_expiryChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onday_to_expiryChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property create_uid() As Nullable(Of Global.System.Int32)
        Get
            Return _create_uid
        End Get
        Set
            Oncreate_uidChanging(value)
            ReportPropertyChanging("create_uid")
            _create_uid = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("create_uid")
            Oncreate_uidChanged()
        End Set
    End Property

    Private _create_uid As Nullable(Of Global.System.Int32)
    Private Partial Sub Oncreate_uidChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Oncreate_uidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property create_date() As Nullable(Of Global.System.DateTime)
        Get
            Return _create_date
        End Get
        Set
            Oncreate_dateChanging(value)
            ReportPropertyChanging("create_date")
            _create_date = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("create_date")
            Oncreate_dateChanged()
        End Set
    End Property

    Private _create_date As Nullable(Of Global.System.DateTime)
    Private Partial Sub Oncreate_dateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Oncreate_dateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property write_uid() As Nullable(Of Global.System.Int32)
        Get
            Return _write_uid
        End Get
        Set
            Onwrite_uidChanging(value)
            ReportPropertyChanging("write_uid")
            _write_uid = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("write_uid")
            Onwrite_uidChanged()
        End Set
    End Property

    Private _write_uid As Nullable(Of Global.System.Int32)
    Private Partial Sub Onwrite_uidChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onwrite_uidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property write_date() As Nullable(Of Global.System.DateTime)
        Get
            Return _write_date
        End Get
        Set
            Onwrite_dateChanging(value)
            ReportPropertyChanging("write_date")
            _write_date = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("write_date")
            Onwrite_dateChanged()
        End Set
    End Property

    Private _write_date As Nullable(Of Global.System.DateTime)
    Private Partial Sub Onwrite_dateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Onwrite_dateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int64
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int64
    Private Partial Sub OnidChanging(value As Global.System.Int64)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MrpPosModel", Name:="product_case")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class product_case
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new product_case object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    Public Shared Function Createproduct_case(id As Global.System.Int64) As product_case
        Dim product_case as product_case = New product_case
        product_case.id = id
        Return product_case
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property product_id() As Nullable(Of Global.System.Int64)
        Get
            Return _product_id
        End Get
        Set
            Onproduct_idChanging(value)
            ReportPropertyChanging("product_id")
            _product_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("product_id")
            Onproduct_idChanged()
        End Set
    End Property

    Private _product_id As Nullable(Of Global.System.Int64)
    Private Partial Sub Onproduct_idChanging(value As Nullable(Of Global.System.Int64))
    End Sub

    Private Partial Sub Onproduct_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property pcs_per_case() As Nullable(Of Global.System.Int32)
        Get
            Return _pcs_per_case
        End Get
        Set
            Onpcs_per_caseChanging(value)
            ReportPropertyChanging("pcs_per_case")
            _pcs_per_case = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("pcs_per_case")
            Onpcs_per_caseChanged()
        End Set
    End Property

    Private _pcs_per_case As Nullable(Of Global.System.Int32)
    Private Partial Sub Onpcs_per_caseChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onpcs_per_caseChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property case_product_id() As Nullable(Of Global.System.Int64)
        Get
            Return _case_product_id
        End Get
        Set
            Oncase_product_idChanging(value)
            ReportPropertyChanging("case_product_id")
            _case_product_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("case_product_id")
            Oncase_product_idChanged()
        End Set
    End Property

    Private _case_product_id As Nullable(Of Global.System.Int64)
    Private Partial Sub Oncase_product_idChanging(value As Nullable(Of Global.System.Int64))
    End Sub

    Private Partial Sub Oncase_product_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property write_uid() As Nullable(Of Global.System.Int32)
        Get
            Return _write_uid
        End Get
        Set
            Onwrite_uidChanging(value)
            ReportPropertyChanging("write_uid")
            _write_uid = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("write_uid")
            Onwrite_uidChanged()
        End Set
    End Property

    Private _write_uid As Nullable(Of Global.System.Int32)
    Private Partial Sub Onwrite_uidChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onwrite_uidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property write_date() As Nullable(Of Global.System.DateTime)
        Get
            Return _write_date
        End Get
        Set
            Onwrite_dateChanging(value)
            ReportPropertyChanging("write_date")
            _write_date = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("write_date")
            Onwrite_dateChanged()
        End Set
    End Property

    Private _write_date As Nullable(Of Global.System.DateTime)
    Private Partial Sub Onwrite_dateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Onwrite_dateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property create_uid() As Nullable(Of Global.System.Int32)
        Get
            Return _create_uid
        End Get
        Set
            Oncreate_uidChanging(value)
            ReportPropertyChanging("create_uid")
            _create_uid = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("create_uid")
            Oncreate_uidChanged()
        End Set
    End Property

    Private _create_uid As Nullable(Of Global.System.Int32)
    Private Partial Sub Oncreate_uidChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Oncreate_uidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property create_date() As Nullable(Of Global.System.DateTime)
        Get
            Return _create_date
        End Get
        Set
            Oncreate_dateChanging(value)
            ReportPropertyChanging("create_date")
            _create_date = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("create_date")
            Oncreate_dateChanged()
        End Set
    End Property

    Private _create_date As Nullable(Of Global.System.DateTime)
    Private Partial Sub Oncreate_dateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Oncreate_dateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int64
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int64
    Private Partial Sub OnidChanging(value As Global.System.Int64)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MrpPosModel", Name:="product_product")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class product_product
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new product_product object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    Public Shared Function Createproduct_product(id As Global.System.Int64) As product_product
        Dim product_product as product_product = New product_product
        product_product.id = id
        Return product_product
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int64
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int64
    Private Partial Sub OnidChanging(value As Global.System.Int64)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property name() As Global.System.String
        Get
            Return _name
        End Get
        Set
            OnnameChanging(value)
            ReportPropertyChanging("name")
            _name = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("name")
            OnnameChanged()
        End Set
    End Property

    Private _name As Global.System.String
    Private Partial Sub OnnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property name2() As Global.System.String
        Get
            Return _name2
        End Get
        Set
            Onname2Changing(value)
            ReportPropertyChanging("name2")
            _name2 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("name2")
            Onname2Changed()
        End Set
    End Property

    Private _name2 As Global.System.String
    Private Partial Sub Onname2Changing(value As Global.System.String)
    End Sub

    Private Partial Sub Onname2Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ean13() As Global.System.String
        Get
            Return _ean13
        End Get
        Set
            Onean13Changing(value)
            ReportPropertyChanging("ean13")
            _ean13 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ean13")
            Onean13Changed()
        End Set
    End Property

    Private _ean13 As Global.System.String
    Private Partial Sub Onean13Changing(value As Global.System.String)
    End Sub

    Private Partial Sub Onean13Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property code() As Global.System.String
        Get
            Return _code
        End Get
        Set
            OncodeChanging(value)
            ReportPropertyChanging("code")
            _code = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("code")
            OncodeChanged()
        End Set
    End Property

    Private _code As Global.System.String
    Private Partial Sub OncodeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OncodeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property price_per_kg() As Nullable(Of Global.System.Int64)
        Get
            Return _price_per_kg
        End Get
        Set
            Onprice_per_kgChanging(value)
            ReportPropertyChanging("price_per_kg")
            _price_per_kg = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("price_per_kg")
            Onprice_per_kgChanged()
        End Set
    End Property

    Private _price_per_kg As Nullable(Of Global.System.Int64)
    Private Partial Sub Onprice_per_kgChanging(value As Nullable(Of Global.System.Int64))
    End Sub

    Private Partial Sub Onprice_per_kgChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property is_case_product() As Nullable(Of Global.System.Int32)
        Get
            Return _is_case_product
        End Get
        Set
            Onis_case_productChanging(value)
            ReportPropertyChanging("is_case_product")
            _is_case_product = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("is_case_product")
            Onis_case_productChanged()
        End Set
    End Property

    Private _is_case_product As Nullable(Of Global.System.Int32)
    Private Partial Sub Onis_case_productChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onis_case_productChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property image() As Global.System.String
        Get
            Return _image
        End Get
        Set
            OnimageChanging(value)
            ReportPropertyChanging("image")
            _image = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("image")
            OnimageChanged()
        End Set
    End Property

    Private _image As Global.System.String
    Private Partial Sub OnimageChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnimageChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property day_to_expire() As Nullable(Of Global.System.Int32)
        Get
            Return _day_to_expire
        End Get
        Set
            Onday_to_expireChanging(value)
            ReportPropertyChanging("day_to_expire")
            _day_to_expire = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("day_to_expire")
            Onday_to_expireChanged()
        End Set
    End Property

    Private _day_to_expire As Nullable(Of Global.System.Int32)
    Private Partial Sub Onday_to_expireChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onday_to_expireChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property weight_type() As Nullable(Of Global.System.Int32)
        Get
            Return _weight_type
        End Get
        Set
            Onweight_typeChanging(value)
            ReportPropertyChanging("weight_type")
            _weight_type = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("weight_type")
            Onweight_typeChanged()
        End Set
    End Property

    Private _weight_type As Nullable(Of Global.System.Int32)
    Private Partial Sub Onweight_typeChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onweight_typeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property create_date() As Nullable(Of Global.System.DateTime)
        Get
            Return _create_date
        End Get
        Set
            Oncreate_dateChanging(value)
            ReportPropertyChanging("create_date")
            _create_date = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("create_date")
            Oncreate_dateChanged()
        End Set
    End Property

    Private _create_date As Nullable(Of Global.System.DateTime)
    Private Partial Sub Oncreate_dateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Oncreate_dateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property create_uid() As Nullable(Of Global.System.Int32)
        Get
            Return _create_uid
        End Get
        Set
            Oncreate_uidChanging(value)
            ReportPropertyChanging("create_uid")
            _create_uid = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("create_uid")
            Oncreate_uidChanged()
        End Set
    End Property

    Private _create_uid As Nullable(Of Global.System.Int32)
    Private Partial Sub Oncreate_uidChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Oncreate_uidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property write_date() As Nullable(Of Global.System.DateTime)
        Get
            Return _write_date
        End Get
        Set
            Onwrite_dateChanging(value)
            ReportPropertyChanging("write_date")
            _write_date = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("write_date")
            Onwrite_dateChanged()
        End Set
    End Property

    Private _write_date As Nullable(Of Global.System.DateTime)
    Private Partial Sub Onwrite_dateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Onwrite_dateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property write_uid() As Nullable(Of Global.System.Int32)
        Get
            Return _write_uid
        End Get
        Set
            Onwrite_uidChanging(value)
            ReportPropertyChanging("write_uid")
            _write_uid = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("write_uid")
            Onwrite_uidChanged()
        End Set
    End Property

    Private _write_uid As Nullable(Of Global.System.Int32)
    Private Partial Sub Onwrite_uidChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onwrite_uidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ean13font() As Global.System.String
        Get
            Return _ean13font
        End Get
        Set
            Onean13fontChanging(value)
            ReportPropertyChanging("ean13font")
            _ean13font = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ean13font")
            Onean13fontChanged()
        End Set
    End Property

    Private _ean13font As Global.System.String
    Private Partial Sub Onean13fontChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onean13fontChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property no_of_barcode() As Nullable(Of Global.System.Int32)
        Get
            Return _no_of_barcode
        End Get
        Set
            Onno_of_barcodeChanging(value)
            ReportPropertyChanging("no_of_barcode")
            _no_of_barcode = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("no_of_barcode")
            Onno_of_barcodeChanged()
        End Set
    End Property

    Private _no_of_barcode As Nullable(Of Global.System.Int32)
    Private Partial Sub Onno_of_barcodeChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onno_of_barcodeChanged()
    End Sub

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MrpPosModel", Name:="user_user")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class user_user
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new user_user object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    Public Shared Function Createuser_user(id As Global.System.Int64) As user_user
        Dim user_user as user_user = New user_user
        user_user.id = id
        Return user_user
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property user_name() As Global.System.String
        Get
            Return _user_name
        End Get
        Set
            Onuser_nameChanging(value)
            ReportPropertyChanging("user_name")
            _user_name = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("user_name")
            Onuser_nameChanged()
        End Set
    End Property

    Private _user_name As Global.System.String
    Private Partial Sub Onuser_nameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onuser_nameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property user_id() As Global.System.String
        Get
            Return _user_id
        End Get
        Set
            Onuser_idChanging(value)
            ReportPropertyChanging("user_id")
            _user_id = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("user_id")
            Onuser_idChanged()
        End Set
    End Property

    Private _user_id As Global.System.String
    Private Partial Sub Onuser_idChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onuser_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property password() As Global.System.String
        Get
            Return _password
        End Get
        Set
            OnpasswordChanging(value)
            ReportPropertyChanging("password")
            _password = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("password")
            OnpasswordChanged()
        End Set
    End Property

    Private _password As Global.System.String
    Private Partial Sub OnpasswordChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnpasswordChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property user_ean13() As Global.System.String
        Get
            Return _user_ean13
        End Get
        Set
            Onuser_ean13Changing(value)
            ReportPropertyChanging("user_ean13")
            _user_ean13 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("user_ean13")
            Onuser_ean13Changed()
        End Set
    End Property

    Private _user_ean13 As Global.System.String
    Private Partial Sub Onuser_ean13Changing(value As Global.System.String)
    End Sub

    Private Partial Sub Onuser_ean13Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property create_uid() As Nullable(Of Global.System.Int32)
        Get
            Return _create_uid
        End Get
        Set
            Oncreate_uidChanging(value)
            ReportPropertyChanging("create_uid")
            _create_uid = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("create_uid")
            Oncreate_uidChanged()
        End Set
    End Property

    Private _create_uid As Nullable(Of Global.System.Int32)
    Private Partial Sub Oncreate_uidChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Oncreate_uidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property create_date() As Nullable(Of Global.System.DateTime)
        Get
            Return _create_date
        End Get
        Set
            Oncreate_dateChanging(value)
            ReportPropertyChanging("create_date")
            _create_date = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("create_date")
            Oncreate_dateChanged()
        End Set
    End Property

    Private _create_date As Nullable(Of Global.System.DateTime)
    Private Partial Sub Oncreate_dateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Oncreate_dateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property write_uid() As Nullable(Of Global.System.Int32)
        Get
            Return _write_uid
        End Get
        Set
            Onwrite_uidChanging(value)
            ReportPropertyChanging("write_uid")
            _write_uid = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("write_uid")
            Onwrite_uidChanged()
        End Set
    End Property

    Private _write_uid As Nullable(Of Global.System.Int32)
    Private Partial Sub Onwrite_uidChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onwrite_uidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property write_Date() As Nullable(Of Global.System.DateTime)
        Get
            Return _write_Date
        End Get
        Set
            Onwrite_DateChanging(value)
            ReportPropertyChanging("write_Date")
            _write_Date = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("write_Date")
            Onwrite_DateChanged()
        End Set
    End Property

    Private _write_Date As Nullable(Of Global.System.DateTime)
    Private Partial Sub Onwrite_DateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Onwrite_DateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int64
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int64
    Private Partial Sub OnidChanging(value As Global.System.Int64)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    #End Region
End Class

#End Region

